---
title: "Formative Assesment 7"
author: "Dwight Gonzales"
output: pdf_document
---
#Number 1
```{r}
theta <- 4
prob_a <- 1-pexp(0.25, rate = theta)
prob_b <- pexp(0.5, rate = theta)
prob_c <- pexp(1, rate = theta) - pexp(0.25, rate = theta)

barplot(c(prob_a, prob_b, prob_c), col = "skyblue", main = "Exponential Distribution Probabilities",
        ylab = "Probability", ylim = c(0, 1.2), names.arg = c("a", "b", "c"))

text(1:3, c(prob_a, prob_b, prob_c), labels = sprintf("%.3f", c(prob_a, prob_b, prob_c)), pos = 3, col = "red")


```

#Number 2
```{r}

#a
prob_more_than_2jobs <- 1 - ppois(2, 2)
prob_more_than_2jobs
#b
prob_atleast_than_30s_elapse <- 1 - pexp(0.5, 2)
prob_atleast_than_30s_elapse
#c

prob_less_than_30s_elapse <- 1 - exp(-2 * .5)
prob_less_than_30s_elapse

#d
prob_job_in_next_30s <- 1 - pexp(0.5, 2)
prob_job_in_next_30s
```

#Number 3

```{r}
lambda <- 15 / 60
prob_no_visit_10_minutes <- dpois(0, lambda)
prob_no_visit_10_minutes
lambda_hourly <- 15
prob_less_than_8_visits <- ppois(7, lambda_hourly)
prob_less_than_8_visits
top_quartile <- qpois(0.75, lambda_hourly)
top_quartile
```