---
title: "Summative Assessment"
output: rmarkdown::github_document
---

```{r}
calc_defective_prob <- function(x1, x2, x3, y1, y2, y3) {
  if (is.na(x1) || is.na(x2) || is.na(x3) || is.na(y1) || is.na(y2) || is.na(y3)) {
    print("Please enter numeric values!")
    return(NULL)
  }
  
  if (!(0.1 <= x1 && x1 <= 0.4 && 0.1 <= x2 && x2 <= 0.4 && 0.1 <= x3 && x3 <= 0.4)) {
    print("Please input values between 0.1 to 0.4!")
    return(NULL)
  }
  
  if (!(0.01 <= y1 && y1 <= 0.05 && 0.01 <= y2 && y2 <= 0.05 && 0.01 <= y3 && y3 <= 0.05)) {
    print("Please input values between 0.01 to 0.05!")
    return(NULL)
  }
  
  total_defective_products <- x1 * y1 + x2 * y2 + x3 * y3
  total_products <- x1 + x2 + x3
  prob_defective_prod <- total_defective_products / total_products
  
  return(prob_defective_prod)
}

x1 <- 0.3
x2 <- 0.2
x3 <- 0.1
y1 <- 0.03
y2 <- 0.04
y3 <- 0.02

#x1 <- as.numeric(readline(prompt = "Enter x1 (0.1 to 0.4): "))
#x2 <- as.numeric(readline(prompt = "Enter x2 (0.1 to 0.4): "))
#x3 <- as.numeric(readline(prompt = "Enter x3 (0.1 to 0.4): "))
#y1 <- as.numeric(readline(prompt = "Enter y1 (0.01 to 0.05): "))
#y2 <- as.numeric(readline(prompt = "Enter y2 (0.01 to 0.05): "))
#y3 <- as.numeric(readline(prompt = "Enter y3 (0.01 to 0.05): "))


prob <- calc_defective_prob(x1, x2, x3, y1, y2, y3)

if (!is.null(prob)) {
  print(sprintf("The probability that a randomly selected product is defective is: %.2f%%", prob * 100))
}


